export interface juegos{
    Id_Juego: number,
    Id_Plataforma: number,
    Id_Genero: number ,
    Descripcion: string,        
    Portada: string,
    Valoracion: number,
    NumValoraciones: number,
    Precio: number,
    Edicion: string,
    Stock: Date,
    Lanzamiento:Date,
    Imagenes: string,
    Video: string,
    EdadMin: number, 
    Nombre_Genero: string ,
    Nombre_Juego: string,
    Nombre_Plataforma: string,   
}